"""
Debate Manager for Web UI.
Handles the orchestration of the debate and WebSocket communication.
"""

import asyncio
import json
import logging
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional

from agents.evidence.devils_advocate import DevilsAdvocateAgent
from agents.evidence.fact_checker import FactCheckerAgent
from agents.moderator import ModeratorAgent
from agents.perspectives.conservative import ConservativeAgent
from agents.perspectives.progressive import ProgressiveAgent
from agents.synthesis.analyzer import ArgumentAnalyzerAgent
from agents.synthesis.common_ground import CommonGroundFinder
from agents.synthesis.synthesizer import SynthesizerAgent
from config import settings
from memory.memory_bank import MemoryBank
from protocols.message_format import DebateMessage, MessageType
from utils.metrics import MetricsCollector

logger = logging.getLogger(__name__)


class DebateManager:
    """
    Manages a single debate session, coordinating agents and WebSocket updates.
    """

    def __init__(self, broadcast_func: Callable[[Dict[str, Any]], None]):
        self.broadcast = broadcast_func
        self.is_running = False
        self.should_stop = False
        self.debate_id = None
        self.memory = None
        self.metrics_collector = None

        # Agents
        self.moderator = None
        self.conservative = None
        self.progressive = None
        self.fact_checker = None
        self.devils_advocate = None
        self.analyzer = None
        self.synthesizer = None
        self.common_ground = None

    async def initialize_agents(self):
        """Initialize all agents."""
        logger.info("Initializing agents...")
        self.moderator = ModeratorAgent()
        self.conservative = ConservativeAgent()
        self.progressive = ProgressiveAgent()
        self.fact_checker = FactCheckerAgent()
        self.devils_advocate = DevilsAdvocateAgent()
        self.analyzer = ArgumentAnalyzerAgent()
        self.synthesizer = SynthesizerAgent()
        self.common_ground = CommonGroundFinder()
        logger.info("Agents initialized.")

    async def start_debate(
        self,
        topic: str,
        rounds: int = 2,
        active_agents: List[str] = None,
        debate_id: Optional[str] = None,
    ):
        """Start the debate loop in the background."""
        if self.is_running:
            logger.warning("Debate already running")
            return

        self.is_running = True
        self.should_stop = False

        # Initialize Memory & Metrics
        self.memory = MemoryBank()
        # If debate_id provided, override the one generated by MemoryBank
        if debate_id:
            self.memory.debate_id = debate_id

        self.debate_id = self.memory.debate_id
        self.metrics_collector = MetricsCollector(self.debate_id)

        # Agents should already be initialized in server startup (lifespan)
        # If not, log error instead of blocking API endpoint
        if not self.moderator:
            logger.error("Agents not initialized! This should never happen.")
            raise RuntimeError("Agents must be initialized before starting debate")

        # Run debate loop in background - don't await it!
        asyncio.create_task(self._run_debate_wrapper(topic, rounds))

        # Return immediately so API endpoint doesn't block
        logger.info(f"Debate {self.debate_id} started in background")

    async def _run_debate_wrapper(self, topic: str, rounds: int):
        """Wrapper to run debate loop with error handling."""
        # Give time for WebSocket connections to establish before starting debate
        await asyncio.sleep(2.0)  # 2 seconds delay

        try:
            await self._run_debate_loop(topic, rounds)
        except Exception as e:
            logger.error(f"Debate error: {e}")
            await self.broadcast({"type": "ERROR", "content": str(e)})
        finally:
            self.is_running = False
            await self.broadcast({"type": "STATUS", "status": "stopped"})

    async def stop_debate(self):
        """Signal the debate to stop."""
        self.should_stop = True
        self.is_running = False

    async def _run_debate_loop(self, topic: str, rounds: int):
        """Main debate execution loop."""
        await self.broadcast(
            {"type": "STATUS", "status": "running", "debate_id": self.debate_id, "topic": topic}
        )

        # -- Opening --
        logger.info("Moderator Opening...")
        opening_prompt = f"Welcome everyone. Please provide an opening statement for the debate on '{topic}'. Introduce the topic and the participants: Conservative and Progressive."

        opening_text = await self.moderator.generate_response(
            "", opening_prompt, self.metrics_collector
        )

        opening_msg = DebateMessage(
            from_agent=self.moderator.name,
            role=self.moderator.role,
            content=opening_text,
            type=MessageType.OPENING_STATEMENT,
        )
        self.memory.add_message(opening_msg)
        await self.broadcast(opening_msg.to_dict())
        await asyncio.sleep(0)  # Yield to event loop to flush WebSocket

        # -- Rounds --
        for round_num in range(1, rounds + 1):
            if self.should_stop:
                break

            await self.broadcast({"type": "ROUND_START", "round": round_num})
            await asyncio.sleep(0)  # Yield to event loop

            # 1. Conservative Turn
            await self._handle_turn(self.conservative, round_num, run_devil_advocate=False)
            if self.should_stop:
                break

            # Delay between agents to avoid API overload
            await asyncio.sleep(settings.agent_delay_seconds)

            # 2. Progressive Turn
            await self._handle_turn(self.progressive, round_num, run_devil_advocate=False)
            if self.should_stop:
                break

            # Run Devil's Advocate ONCE per round (after both agents)
            await self._run_devils_advocate_round()

            # Delay before next round
            await asyncio.sleep(settings.agent_delay_seconds)

        # -- Synthesis --
        if not self.should_stop:
            await self._run_synthesis(topic)

        # -- Save --
        metrics = self.metrics_collector.get_metrics_dict()
        saved_path = self.memory.save_debate(metrics=metrics)
        logger.info(f"Debate saved to {saved_path}")

        await self.broadcast({"type": "SYSTEM", "content": f"Debate saved to {saved_path}"})

    async def _handle_turn(self, agent, round_num, run_devil_advocate=True):
        """Handle a single agent's turn including analysis."""
        history = self.memory.get_full_history()

        # Generate Response
        response_data = await agent.process_message(history[-1].to_dict())
        msg = DebateMessage(**response_data)
        msg.round_number = round_num

        # Check if response is an error message (format: [AgentName - error message])
        is_error = (
            msg.content.startswith("[") and " - " in msg.content and msg.content.endswith("]")
        )

        if is_error:
            # Handle error: don't add to memory, broadcast as ERROR type
            logger.warning(f"Agent {agent.name} produced error: {msg.content}")

            await self.broadcast(
                {
                    "type": "ERROR",
                    "from_agent": agent.name,
                    "content": msg.content,
                    "round_number": round_num,
                }
            )
            await asyncio.sleep(0)

            # Log error to metrics
            if self.metrics_collector:
                self.metrics_collector.track_action(
                    agent_name=agent.name,
                    action_type="agent_turn_error",
                    start_time=0,
                    input_text="",
                    output_text=msg.content,
                    error=Exception(msg.content),
                )

            # Don't continue with analysis for error messages
            return

        # Normal flow: add to memory and broadcast
        self.memory.add_message(msg)
        await self.broadcast(msg.to_dict())
        await asyncio.sleep(0)  # Yield to event loop

        # Parallel Analysis (only for valid messages)
        await self._run_analysis(msg, run_devil_advocate=run_devil_advocate)

    async def _run_analysis(self, message: DebateMessage, run_devil_advocate=True):
        """Run Fact Checker, Devil's Advocate, and Analyzer in parallel."""
        # We don't want analysis to block the flow too much, but for now we await it
        # to ensure the UI gets updates in order.

        # 1. Fact Check
        try:
            fc_res = await self.fact_checker.check_claim(message.content)
            if fc_res["verdict"] != "TRUE":
                fc_msg = {
                    "type": "FACT_CHECK",
                    "from_agent": self.fact_checker.name,
                    "content": fc_res["explanation"],
                    "claim": message.content[:100] + "...",
                    "verdict": fc_res["verdict"],
                }
                await self.broadcast(fc_msg)
                await asyncio.sleep(0)  # Yield to event loop
        except Exception as e:
            logger.error(f"❌ Fact Checker analysis error: {e}", exc_info=True)

        # 2. Devil's Advocate (only if enabled for this turn)
        if run_devil_advocate:
            try:
                da_res = await self.devils_advocate.challenge_argument(message.content, message.from_agent)
                if da_res:
                    # Devil's Advocate returns 'question', not 'challenge'
                    da_msg = {
                        "type": "CHALLENGE",
                        "from_agent": self.devils_advocate.name,
                        "content": da_res.get("question", da_res.get("challenge", "Challenge unavailable")),
                        "challenge_type": da_res.get("challenge_type", "unknown"),
                    }
                    await self.broadcast(da_msg)
                    await asyncio.sleep(0)  # Yield to event loop
            except Exception as e:
                logger.error(f"❌ Devil's Advocate challenge error: {e}", exc_info=True)

    async def _run_devils_advocate_round(self):
        """Run Devil's Advocate once per round on one random message."""
        history = self.memory.get_full_history()
        if len(history) < 2:
            return

        # Get the last 2 arguments (both agents from this round)
        recent_args = [msg for msg in history[-2:] if msg.type in ["ARGUMENT", "REBUTTAL", "OPENING_STATEMENT"]]
        
        if not recent_args:
            return

        # Pick ONE random argument to challenge per round
        import random
        msg = random.choice(recent_args)

        try:
            da_res = await self.devils_advocate.challenge_argument(msg.content, msg.from_agent)
            if da_res:
                da_msg = {
                    "type": "CHALLENGE",
                    "from_agent": self.devils_advocate.name,
                    "content": da_res.get("question", da_res.get("challenge", "Challenge unavailable")),
                    "challenge_type": da_res.get("challenge_type", "unknown"),
                }
                await self.broadcast(da_msg)
                await asyncio.sleep(0)
        except Exception as e:
            logger.error(f"❌ Devil's Advocate round challenge error: {e}", exc_info=True)

    async def _run_synthesis(self, topic: str):
        """Run synthesis phase."""
        await self.broadcast({"type": "STATUS", "status": "synthesizing"})

        history = self.memory.get_full_history()

        # Common Ground
        cg_result = await self.common_ground.find_common_ground(history, topic)

        # Final Synthesis
        synth_result = await self.synthesizer.synthesize_debate(history, topic)

        # Broadcast Synthesis Result (frontend will display it)
        await self.broadcast(
            {"type": "SYNTHESIS", "common_ground": cg_result, "synthesis": synth_result}
        )
        await asyncio.sleep(0)  # Yield to event loop
